import { fireEvent, render, screen, waitFor } from '@testing-library/react'
import { beforeEach, describe, expect, it, vi } from 'vitest'

const state=vi.hoisted(()=>({cart:null as unknown,items:[] as unknown[],loading:false,error:null as string|null,removeItem:vi.fn(),replaceCart:vi.fn(),push:vi.fn()}))
vi.mock('@/lib/cart-context',()=>({useCart:()=>state}))
vi.mock('next/navigation',()=>({useRouter:()=>({push:state.push})}))
import { CartDraftFlow } from '@/components/cart-draft-flow'

const cities=[{id:'city',name:'Saltillo',state:'Coahuila'}];const zones=[{id:'zone',cityId:'city',name:'Centro'}]
describe('cart to draft customer flow',()=>{
  beforeEach(()=>{state.cart=null;state.items=[];state.loading=false;state.error=null;vi.clearAllMocks()})
  it('renders the empty state',()=>{render(<CartDraftFlow cities={cities} zones={zones}/>);expect(screen.getByText('Tu carrito está vacío')).toBeInTheDocument()})
  it('renders recipient, address, personalization, date, summary, and draft-only notice',()=>{state.cart={id:'cart',status:'active',version:1,requestedDeliveryAt:null,convertedOrderId:null,items:[],recipient:null,address:null};state.items=[{id:'item',listingId:'listing',name:'Rosas',slug:'rosas',variantId:null,quantity:1,options:[],personalization:null}];render(<CartDraftFlow cities={cities} zones={zones}/>);expect(screen.getAllByText('Destinatario').length).toBeGreaterThan(0);expect(screen.getByText('Dirección solicitada')).toBeInTheDocument();expect(screen.getByText('Fecha solicitada')).toBeInTheDocument();expect(screen.getByLabelText('Dedicatoria')).toBeInTheDocument();expect(screen.getByText(/Este pedido es un borrador/)).toBeInTheDocument();expect(screen.queryByText(/Mercado Pago/i)).not.toBeInTheDocument()})
  it('hydrates saved recipient, address, and requested date',async()=>{state.cart={id:'cart',status:'active',version:4,requestedDeliveryAt:'2026-07-17T20:00:00.000Z',convertedOrderId:null,items:[],recipient:{sourceRecipientId:null,name:'Destinatario guardado',relationship:'Amistad',phone:'8440000000',surpriseMode:'none',deliveryNote:null},address:{sourceAddressId:null,label:null,street:'Calle guardada',exteriorNumber:'100',interiorNumber:null,neighborhood:'Centro',postalCode:'25000',cityId:'city',zoneId:'zone',state:'Coahuila',countryCode:'MX',references:null}};state.items=[{id:'item',listingId:'listing',name:'Rosas',slug:'rosas',variantId:null,quantity:1,options:[],personalization:null}];render(<CartDraftFlow cities={cities} zones={zones}/>);await waitFor(()=>expect(screen.getByPlaceholderText('Nombre *')).toHaveValue('Destinatario guardado'));expect(screen.getByPlaceholderText('Calle *')).toHaveValue('Calle guardada');expect(document.querySelector('input[type="datetime-local"]')).toHaveValue('2026-07-17T14:00')})
  it('does not enable draft creation with incomplete data',()=>{state.cart={id:'cart',status:'active',version:1,requestedDeliveryAt:null,convertedOrderId:null,items:[],recipient:null,address:null};state.items=[{id:'item',listingId:'listing',name:'Rosas',slug:'rosas',variantId:null,quantity:1,options:[],personalization:null}];render(<CartDraftFlow cities={cities} zones={zones}/>);expect(screen.getByRole('button',{name:'Crear pedido borrador'})).toBeDisabled()})
  it('enforces the technical quantity range in the UI',()=>{state.cart={id:'cart',status:'active',version:1,requestedDeliveryAt:null,convertedOrderId:null,items:[],recipient:null,address:null};state.items=[{id:'item',listingId:'listing',name:'Rosas',slug:'rosas',variantId:null,quantity:1,options:[],personalization:null}];render(<CartDraftFlow cities={cities} zones={zones}/>);const quantity=screen.getByRole('spinbutton',{name:'Cantidad'});fireEvent.change(quantity,{target:{value:'21'}});expect(screen.getByRole('button',{name:'Guardar artículo'})).toBeDisabled()})
})
