BEGIN;
SELECT plan(28);
SELECT has_table('public','payment_attempts','payment attempts exist');
SELECT has_table('public','payment_provider_events','provider event inbox exists');
SELECT has_column('public','orders','active_payment_attempt_id','order has active attempt link');
SELECT has_column('public','orders','paid_at','order has paid timestamp');
SELECT col_is_fk('public','payment_attempts','order_id','attempt order is restricted by FK');
SELECT col_is_fk('public','payment_attempts','quote_id','attempt quote is restricted by FK');
SELECT col_is_fk('public','payment_attempts','customer_id','attempt customer is restricted by FK');
SELECT table_privs_are('public','payment_attempts','anon',ARRAY[]::text[],'anon has no attempt privileges');
SELECT table_privs_are('public','payment_attempts','authenticated',ARRAY[]::text[],'browser has no attempt privileges');
SELECT table_privs_are('public','payment_provider_events','anon',ARRAY[]::text[],'anon has no event privileges');
SELECT table_privs_are('public','payment_provider_events','authenticated',ARRAY[]::text[],'browser has no event privileges');
SELECT policies_are('public','payment_attempts',ARRAY[]::text[],'attempts are default deny');
SELECT policies_are('public','payment_provider_events',ARRAY[]::text[],'events are default deny');
SELECT has_function('public','begin_payment_checkout',ARRAY['uuid','uuid','integer','text','uuid','text','integer'],'checkout begin command exists');
SELECT has_function('public','complete_payment_checkout',ARRAY['uuid','text','text','timestamp with time zone','uuid'],'checkout completion command exists');
SELECT has_function('public','process_provider_payment',ARRAY['uuid','jsonb','text','text'],'authoritative processor exists');
SELECT has_function('public','payment_requery_target',ARRAY['uuid','uuid','boolean'],'requery command exists');
SELECT function_privs_are('public','begin_payment_checkout',ARRAY['uuid','uuid','integer','text','uuid','text','integer'],'authenticated',ARRAY[]::text[],'browser cannot begin directly');
SELECT function_privs_are('public','process_provider_payment',ARRAY['uuid','jsonb','text','text'],'authenticated',ARRAY[]::text[],'browser cannot process provider data');
SELECT function_privs_are('public','list_central_payments',ARRAY[]::text[],'authenticated',ARRAY['EXECUTE']::text[],'Central uses narrow list command');
SELECT function_privs_are('public','get_central_payment',ARRAY['uuid'],'authenticated',ARRAY['EXECUTE']::text[],'Central uses narrow detail command');
SELECT is((SELECT relrowsecurity FROM pg_class WHERE oid='public.payment_attempts'::regclass),true,'attempt RLS enabled');
SELECT is((SELECT relrowsecurity FROM pg_class WHERE oid='public.payment_provider_events'::regclass),true,'event RLS enabled');
SELECT is((SELECT count(*)::integer FROM pg_indexes WHERE schemaname='public' AND indexname='payment_attempts_one_active_idx'),1,'one active attempt index exists');
SELECT is((SELECT count(*)::integer FROM pg_indexes WHERE schemaname='public' AND indexname='payment_attempts_one_approved_idx'),1,'one approved attempt index exists');
SELECT ok(position('paid' in pg_get_constraintdef(oid))>0,'paid constraint mentions paid') FROM pg_constraint WHERE conname='orders_paid_integrity_check';
SELECT is((SELECT proconfig FROM pg_proc WHERE oid='public.process_provider_payment(uuid,jsonb,text,text)'::regprocedure),ARRAY['search_path=""']::text[],'processor search path is empty');
SELECT is((SELECT count(*)::integer FROM pg_enum e JOIN pg_type t ON t.oid=e.enumtypid WHERE t.typname='order_state' AND e.enumlabel IN ('assignment_pending','partner_offered','preparing')),0,'Phase 8 creates no later operational states');
SELECT * FROM finish();
ROLLBACK;
