'use client'

import Link from 'next/link'
import { useEffect, useMemo, useState } from 'react'
import { useRouter } from 'next/navigation'
import { ArrowLeft, CalendarDays, MapPin, PackageOpen, Trash2, UserRound } from 'lucide-react'
import { useCart } from '@/lib/cart-context'
import type { CustomerCart } from '@/lib/cart'

type City={id:string;name:string;state:string};type Zone={id:string;cityId:string;name:string}
const field='w-full rounded-xl border border-border-soft bg-black/20 px-3 py-3 text-sm outline-none focus:border-border-lime'

export function CartDraftFlow({cities,zones}:{cities:City[];zones:Zone[]}){
  const {cart,items,loading,error,removeItem,replaceCart}=useCart();const router=useRouter();const [notice,setNotice]=useState<string|null>(null)
  const [recipient,setRecipient]=useState({name:'',relationship:'',phone:'',surpriseMode:'none',deliveryNote:''})
  const [address,setAddress]=useState({label:'',street:'',exteriorNumber:'',interiorNumber:'',neighborhood:'',postalCode:'',cityId:cities[0]?.id??'',zoneId:'',state:cities[0]?.state??'Coahuila',references:''})
  const [delivery,setDelivery]=useState('');const [busy,setBusy]=useState(false)
  const availableZones=useMemo(()=>zones.filter(zone=>zone.cityId===address.cityId),[address.cityId,zones])
  const recipientSnapshot=JSON.stringify(cart?.recipient??null);const addressSnapshot=JSON.stringify(cart?.address??null)

  useEffect(()=>{const saved=JSON.parse(recipientSnapshot) as CustomerCart['recipient'];if(!saved)return;let active=true;queueMicrotask(()=>{if(active)setRecipient({name:saved.name,relationship:saved.relationship??'',phone:saved.phone??'',surpriseMode:saved.surpriseMode,deliveryNote:saved.deliveryNote??''})});return()=>{active=false}},[recipientSnapshot])
  useEffect(()=>{const saved=JSON.parse(addressSnapshot) as CustomerCart['address'];if(!saved)return;let active=true;queueMicrotask(()=>{if(active)setAddress({label:saved.label??'',street:saved.street,exteriorNumber:saved.exteriorNumber,interiorNumber:saved.interiorNumber??'',neighborhood:saved.neighborhood??'',postalCode:saved.postalCode??'',cityId:saved.cityId,zoneId:saved.zoneId,state:saved.state??'',references:saved.references??''})});return()=>{active=false}},[addressSnapshot])
  useEffect(()=>{if(!cart?.requestedDeliveryAt)return;let active=true;const saved=cart.requestedDeliveryAt;queueMicrotask(()=>{if(active)setDelivery(toLocalDateTimeInput(saved))});return()=>{active=false}},[cart?.requestedDeliveryAt])

  async function mutate(url:string,method:string,payload:Record<string,unknown>){if(!cart)throw new Error('El carrito todavía no existe.');const response=await fetch(url,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify({expectedVersion:cart.version,...payload})});const body=await response.json() as {cart?:CustomerCart;error?:{code?:string;message?:string}};if(!response.ok){if(body.error?.code==='VERSION_CONFLICT')throw new Error('El carrito cambió en otra pestaña. Recarga y revisa los datos.');throw new Error(body.error?.message??'No fue posible guardar.')}if(body.cart)replaceCart(body.cart);return body.cart}
  async function run(action:()=>Promise<unknown>,success:string){setBusy(true);setNotice(null);try{await action();setNotice(success)}catch(cause){setNotice(cause instanceof Error?cause.message:'No fue posible guardar.')}finally{setBusy(false)}}
  async function updateItem(item:CustomerCart['items'][number],values:{quantity:number;recipientName:string;message:string;instructions:string}){await mutate(`/api/cart/items/${item.id}`,'PATCH',{listingId:item.listingId,variantId:item.variantId,optionIds:item.options.map(option=>option.id),quantity:values.quantity,personalization:values.recipientName||values.message||values.instructions?{recipientName:values.recipientName||null,message:values.message||null,instructions:values.instructions||null,spellingConfirmed:true}:null})}
  async function createDraft(){if(!cart)return;setBusy(true);setNotice(null);try{const response=await fetch('/api/orders/draft',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({cartId:cart.id,expectedVersion:cart.version})});const body=await response.json() as {order?:{id:string};error?:{message?:string}};if(!response.ok||!body.order)throw new Error(body.error?.message??'No fue posible crear el borrador.');router.push(`/pedidos/${body.order.id}`)}catch(cause){setNotice(cause instanceof Error?cause.message:'No fue posible crear el borrador.');setBusy(false)}}

  return <main className="min-h-screen px-4 py-6 sm:px-8"><div className="mx-auto max-w-5xl"><header className="flex items-center justify-between"><Link href="/" className="text-xl font-bold tracking-[.35em]">MPHO</Link><Link href="/" className="inline-flex items-center gap-2 text-sm text-muted-foreground"><ArrowLeft className="size-4"/>Seguir explorando</Link></header><div className="mt-10"><p className="text-xs font-bold uppercase tracking-[.22em] text-lime">Fase 6</p><h1 className="mt-2 text-3xl font-extrabold sm:text-5xl">Tu carrito y borrador</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-muted-foreground">Este pedido es un borrador. Precio de entrega, disponibilidad operativa y total final aún pueden requerir revisión.</p></div>
  {(loading&&!cart)?<p className="mt-10" aria-live="polite">Cargando carrito…</p>:items.length===0?<section className="glass mt-10 flex flex-col items-center rounded-3xl p-10 text-center"><PackageOpen className="size-10 text-lime"/><h2 className="mt-4 text-xl font-bold">Tu carrito está vacío</h2><p className="mt-2 text-sm text-muted-foreground">Agrega un regalo real desde el catálogo.</p><Link href="/" className="mt-6 rounded-full bg-lime px-6 py-3 font-bold text-primary-foreground">Explorar regalos</Link></section>:<div className="mt-8 grid gap-6 lg:grid-cols-[1.25fr_.75fr]"><div className="space-y-6">
    <section className="glass rounded-3xl p-5 sm:p-7"><h2 className="text-xl font-bold">Regalos</h2><div className="mt-5 space-y-4">{items.map(item=><CartItemEditor key={item.id} item={item} busy={busy} onSave={values=>run(()=>updateItem(item,values),'Artículo actualizado.')} onRemove={()=>void removeItem(item.id)}/>)}</div></section>
    <section className="glass rounded-3xl p-5 sm:p-7"><h2 className="flex items-center gap-2 text-xl font-bold"><UserRound className="size-5 text-lime"/>Destinatario</h2><div className="mt-5 grid gap-3 sm:grid-cols-2"><input className={field} placeholder="Nombre *" maxLength={120} value={recipient.name} onChange={e=>setRecipient({...recipient,name:e.target.value})}/><input className={field} placeholder="Relación" maxLength={80} value={recipient.relationship} onChange={e=>setRecipient({...recipient,relationship:e.target.value})}/><input className={field} placeholder="Teléfono operativo" maxLength={32} value={recipient.phone} onChange={e=>setRecipient({...recipient,phone:e.target.value})}/><select className={field} value={recipient.surpriseMode} onChange={e=>setRecipient({...recipient,surpriseMode:e.target.value})}><option value="none">Sin sorpresa</option><option value="full_surprise">Sorpresa total</option><option value="partial_surprise">Sorpresa parcial</option></select><textarea className={`${field} sm:col-span-2`} placeholder="Nota de entrega" maxLength={500} value={recipient.deliveryNote} onChange={e=>setRecipient({...recipient,deliveryNote:e.target.value})}/></div><p className="mt-3 text-xs text-muted-foreground">Estos datos se usan para coordinar este pedido; no inscriben al destinatario en marketing.</p><button disabled={busy||!recipient.name.trim()} onClick={()=>void run(()=>mutate('/api/cart/recipient','PUT',{sourceRecipientId:null,...recipient}),'Destinatario guardado en el carrito.')} className="mt-4 rounded-full bg-white/10 px-5 py-2.5 text-sm font-bold disabled:opacity-50">Guardar destinatario</button></section>
    <section className="glass rounded-3xl p-5 sm:p-7"><h2 className="flex items-center gap-2 text-xl font-bold"><MapPin className="size-5 text-lime"/>Dirección solicitada</h2><div className="mt-5 grid gap-3 sm:grid-cols-2"><input className={`${field} sm:col-span-2`} placeholder="Calle *" maxLength={160} value={address.street} onChange={e=>setAddress({...address,street:e.target.value})}/><input className={field} placeholder="Número exterior *" maxLength={30} value={address.exteriorNumber} onChange={e=>setAddress({...address,exteriorNumber:e.target.value})}/><input className={field} placeholder="Interior" maxLength={30} value={address.interiorNumber} onChange={e=>setAddress({...address,interiorNumber:e.target.value})}/><input className={field} placeholder="Colonia" maxLength={120} value={address.neighborhood} onChange={e=>setAddress({...address,neighborhood:e.target.value})}/><input className={field} placeholder="Código postal" maxLength={12} value={address.postalCode} onChange={e=>setAddress({...address,postalCode:e.target.value})}/><select className={field} value={address.cityId} onChange={e=>{const city=cities.find(value=>value.id===e.target.value);setAddress({...address,cityId:e.target.value,zoneId:'',state:city?.state??''})}}>{cities.map(city=><option key={city.id} value={city.id}>{city.name}</option>)}</select><select className={field} value={address.zoneId} onChange={e=>setAddress({...address,zoneId:e.target.value})}><option value="">Selecciona zona *</option>{availableZones.map(zone=><option key={zone.id} value={zone.id}>{zone.name}</option>)}</select><textarea className={`${field} sm:col-span-2`} placeholder="Referencias" maxLength={500} value={address.references} onChange={e=>setAddress({...address,references:e.target.value})}/></div><p className="mt-3 text-xs text-muted-foreground">Seleccionar una zona no confirma cobertura, capacidad ni costo de entrega.</p><button disabled={busy||!address.street.trim()||!address.exteriorNumber.trim()||!address.zoneId} onClick={()=>void run(()=>mutate('/api/cart/address','PUT',{sourceAddressId:null,countryCode:'MX',...address}),'Dirección guardada en el carrito.')} className="mt-4 rounded-full bg-white/10 px-5 py-2.5 text-sm font-bold disabled:opacity-50">Guardar dirección</button></section>
    <section className="glass rounded-3xl p-5 sm:p-7"><h2 className="flex items-center gap-2 text-xl font-bold"><CalendarDays className="size-5 text-lime"/>Fecha solicitada</h2><input type="datetime-local" className={`${field} mt-5`} value={delivery} onChange={e=>setDelivery(e.target.value)}/><p className="mt-3 text-xs text-muted-foreground">Es una solicitud, no una ventana confirmada ni capacidad reservada.</p><button disabled={busy||!delivery} onClick={()=>void run(()=>mutate('/api/cart/delivery','PUT',{requestedDeliveryAt:new Date(delivery).toISOString()}),'Fecha solicitada guardada.')} className="mt-4 rounded-full bg-white/10 px-5 py-2.5 text-sm font-bold disabled:opacity-50">Guardar fecha</button></section>
  </div><aside className="h-fit lg:sticky lg:top-6"><section className="glass rounded-3xl p-6"><h2 className="text-xl font-bold">Resumen</h2><dl className="mt-5 space-y-3 text-sm"><div className="flex justify-between"><dt>Artículos</dt><dd>{items.reduce((sum,item)=>sum+item.quantity,0)}</dd></div><div className="flex justify-between"><dt>Destinatario</dt><dd>{cart?.recipient?'Listo':'Pendiente'}</dd></div><div className="flex justify-between"><dt>Dirección</dt><dd>{cart?.address?'Lista':'Pendiente'}</dd></div><div className="flex justify-between"><dt>Fecha</dt><dd>{cart?.requestedDeliveryAt?'Solicitada':'Pendiente'}</dd></div></dl><div className="mt-6 rounded-2xl border border-border-lime bg-lime/5 p-4 text-xs leading-5 text-muted-foreground">El servidor recalculará catálogo y precios conocidos. No se reservará inventario ni se asignará un aliado.</div><button disabled={busy||!cart?.recipient||!cart.address||!cart.requestedDeliveryAt} onClick={()=>void createDraft()} className="mt-5 w-full rounded-full bg-lime px-5 py-3 font-bold text-primary-foreground disabled:opacity-40">{busy?'Validando…':'Crear pedido borrador'}</button>{(notice||error)&&<p role="alert" className="mt-4 text-sm text-muted-foreground">{notice??error}</p>}</section></aside></div>}</div></main>
}

function toLocalDateTimeInput(value:string){const date=new Date(value);const offset=date.getTimezoneOffset()*60_000;return new Date(date.getTime()-offset).toISOString().slice(0,16)}

function CartItemEditor({item,busy,onSave,onRemove}:{item:CustomerCart['items'][number];busy:boolean;onSave:(values:{quantity:number;recipientName:string;message:string;instructions:string})=>void;onRemove:()=>void}){const[quantity,setQuantity]=useState(item.quantity);const[recipientName,setRecipientName]=useState(item.personalization?.recipientName??'');const[message,setMessage]=useState(item.personalization?.message??'');const[instructions,setInstructions]=useState(item.personalization?.instructions??'');return <article className="rounded-2xl border border-border-soft p-4"><div className="flex items-start justify-between gap-3"><div><Link href={`/producto/${item.slug}`} className="font-bold hover:text-lime">{item.name}</Link><p className="mt-1 text-xs text-muted-foreground">Precio y disponibilidad se recalculan en servidor.</p></div><button aria-label={`Eliminar ${item.name}`} onClick={onRemove} className="text-muted-foreground hover:text-red-300"><Trash2 className="size-4"/></button></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-xs">Cantidad<input className={`${field} mt-1`} type="number" min={1} max={20} value={quantity} onChange={e=>setQuantity(Number(e.target.value))}/></label><label className="text-xs">Nombre en personalización<input className={`${field} mt-1`} maxLength={120} value={recipientName} onChange={e=>setRecipientName(e.target.value)}/></label><label className="text-xs sm:col-span-2">Dedicatoria<textarea className={`${field} mt-1`} maxLength={500} value={message} onChange={e=>setMessage(e.target.value)}/></label><label className="text-xs sm:col-span-2">Instrucciones de texto<textarea className={`${field} mt-1`} maxLength={1000} value={instructions} onChange={e=>setInstructions(e.target.value)}/></label></div><p className="mt-2 text-xs text-muted-foreground">Sólo texto plano. Al guardar confirmas ortografía y contenido.</p><button disabled={busy||quantity<1||quantity>20} onClick={()=>onSave({quantity,recipientName,message,instructions})} className="mt-3 rounded-full bg-white/10 px-4 py-2 text-xs font-bold disabled:opacity-50">Guardar artículo</button></article>}
