// AUTO-GENERATED by `pnpm db:types`. Do not edit manually.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      addresses: {
        Row: {
          archived_at: string | null
          city_id: string
          country_code: string
          created_at: string
          exterior_number: string
          id: string
          interior_number: string | null
          is_default: boolean
          label: string | null
          latitude: number | null
          longitude: number | null
          neighborhood: string | null
          owner_id: string
          owner_type: Database["public"]["Enums"]["address_owner_type"]
          postal_code: string | null
          references_text: string | null
          state: string | null
          street: string
          updated_at: string
        }
        Insert: {
          archived_at?: string | null
          city_id: string
          country_code?: string
          created_at?: string
          exterior_number: string
          id?: string
          interior_number?: string | null
          is_default?: boolean
          label?: string | null
          latitude?: number | null
          longitude?: number | null
          neighborhood?: string | null
          owner_id: string
          owner_type: Database["public"]["Enums"]["address_owner_type"]
          postal_code?: string | null
          references_text?: string | null
          state?: string | null
          street: string
          updated_at?: string
        }
        Update: {
          archived_at?: string | null
          city_id?: string
          country_code?: string
          created_at?: string
          exterior_number?: string
          id?: string
          interior_number?: string | null
          is_default?: boolean
          label?: string | null
          latitude?: number | null
          longitude?: number | null
          neighborhood?: string | null
          owner_id?: string
          owner_type?: Database["public"]["Enums"]["address_owner_type"]
          postal_code?: string | null
          references_text?: string | null
          state?: string | null
          street?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "addresses_city_id_fkey"
            columns: ["city_id"]
            isOneToOne: false
            referencedRelation: "cities"
            referencedColumns: ["id"]
          },
        ]
      }
      cart_delivery_addresses: {
        Row: {
          cart_id: string
          city_id: string
          country_code: string
          created_at: string
          exterior_number: string
          interior_number: string | null
          label: string | null
          neighborhood: string | null
          postal_code: string | null
          references_text: string | null
          source_address_id: string | null
          state: string | null
          street: string
          updated_at: string
          zone_id: string
        }
        Insert: {
          cart_id: string
          city_id: string
          country_code?: string
          created_at?: string
          exterior_number: string
          interior_number?: string | null
          label?: string | null
          neighborhood?: string | null
          postal_code?: string | null
          references_text?: string | null
          source_address_id?: string | null
          state?: string | null
          street: string
          updated_at?: string
          zone_id: string
        }
        Update: {
          cart_id?: string
          city_id?: string
          country_code?: string
          created_at?: string
          exterior_number?: string
          interior_number?: string | null
          label?: string | null
          neighborhood?: string | null
          postal_code?: string | null
          references_text?: string | null
          source_address_id?: string | null
          state?: string | null
          street?: string
          updated_at?: string
          zone_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "cart_delivery_addresses_cart_id_fkey"
            columns: ["cart_id"]
            isOneToOne: true
            referencedRelation: "carts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "cart_delivery_addresses_city_id_fkey"
            columns: ["city_id"]
            isOneToOne: false
            referencedRelation: "cities"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "cart_delivery_addresses_source_address_id_fkey"
            columns: ["source_address_id"]
            isOneToOne: false
            referencedRelation: "addresses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "cart_delivery_addresses_zone_id_fkey"
            columns: ["zone_id"]
            isOneToOne: false
            referencedRelation: "zones"
            referencedColumns: ["id"]
          },
        ]
      }
      cart_item_options: {
        Row: {
          cart_item_id: string
          created_at: string
          option_id: string
        }
        Insert: {
          cart_item_id: string
          created_at?: string
          option_id: string
        }
        Update: {
          cart_item_id?: string
          created_at?: string
          option_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "cart_item_options_cart_item_id_fkey"
            columns: ["cart_item_id"]
            isOneToOne: false
            referencedRelation: "cart_items"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "cart_item_options_option_id_fkey"
            columns: ["option_id"]
            isOneToOne: false
            referencedRelation: "listing_options"
            referencedColumns: ["id"]
          },
        ]
      }
      cart_item_personalizations: {
        Row: {
          approved_at: string | null
          cart_item_id: string
          created_at: string
          instructions: string | null
          message_text: string | null
          recipient_name: string | null
          spelling_confirmed: boolean
          updated_at: string
        }
        Insert: {
          approved_at?: string | null
          cart_item_id: string
          created_at?: string
          instructions?: string | null
          message_text?: string | null
          recipient_name?: string | null
          spelling_confirmed?: boolean
          updated_at?: string
        }
        Update: {
          approved_at?: string | null
          cart_item_id?: string
          created_at?: string
          instructions?: string | null
          message_text?: string | null
          recipient_name?: string | null
          spelling_confirmed?: boolean
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "cart_item_personalizations_cart_item_id_fkey"
            columns: ["cart_item_id"]
            isOneToOne: true
            referencedRelation: "cart_items"
            referencedColumns: ["id"]
          },
        ]
      }
      cart_items: {
        Row: {
          cart_id: string
          created_at: string
          id: string
          listing_id: string
          quantity: number
          updated_at: string
          variant_id: string | null
        }
        Insert: {
          cart_id: string
          created_at?: string
          id?: string
          listing_id: string
          quantity: number
          updated_at?: string
          variant_id?: string | null
        }
        Update: {
          cart_id?: string
          created_at?: string
          id?: string
          listing_id?: string
          quantity?: number
          updated_at?: string
          variant_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "cart_items_cart_id_fkey"
            columns: ["cart_id"]
            isOneToOne: false
            referencedRelation: "carts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "cart_items_listing_id_fkey"
            columns: ["listing_id"]
            isOneToOne: false
            referencedRelation: "listings"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "cart_items_variant_id_fkey"
            columns: ["variant_id"]
            isOneToOne: false
            referencedRelation: "listing_variants"
            referencedColumns: ["id"]
          },
        ]
      }
      cart_recipients: {
        Row: {
          cart_id: string
          created_at: string
          delivery_note: string | null
          name: string
          phone: string | null
          relationship: string | null
          source_recipient_id: string | null
          surprise_mode: Database["public"]["Enums"]["recipient_surprise_mode"]
          updated_at: string
        }
        Insert: {
          cart_id: string
          created_at?: string
          delivery_note?: string | null
          name: string
          phone?: string | null
          relationship?: string | null
          source_recipient_id?: string | null
          surprise_mode?: Database["public"]["Enums"]["recipient_surprise_mode"]
          updated_at?: string
        }
        Update: {
          cart_id?: string
          created_at?: string
          delivery_note?: string | null
          name?: string
          phone?: string | null
          relationship?: string | null
          source_recipient_id?: string | null
          surprise_mode?: Database["public"]["Enums"]["recipient_surprise_mode"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "cart_recipients_cart_id_fkey"
            columns: ["cart_id"]
            isOneToOne: true
            referencedRelation: "carts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "cart_recipients_source_recipient_id_fkey"
            columns: ["source_recipient_id"]
            isOneToOne: false
            referencedRelation: "recipients"
            referencedColumns: ["id"]
          },
        ]
      }
      carts: {
        Row: {
          abandoned_at: string | null
          converted_at: string | null
          converted_order_id: string | null
          created_at: string
          customer_id: string
          id: string
          requested_delivery_at: string | null
          status: Database["public"]["Enums"]["cart_status"]
          updated_at: string
          version: number
        }
        Insert: {
          abandoned_at?: string | null
          converted_at?: string | null
          converted_order_id?: string | null
          created_at?: string
          customer_id: string
          id?: string
          requested_delivery_at?: string | null
          status?: Database["public"]["Enums"]["cart_status"]
          updated_at?: string
          version?: number
        }
        Update: {
          abandoned_at?: string | null
          converted_at?: string | null
          converted_order_id?: string | null
          created_at?: string
          customer_id?: string
          id?: string
          requested_delivery_at?: string | null
          status?: Database["public"]["Enums"]["cart_status"]
          updated_at?: string
          version?: number
        }
        Relationships: [
          {
            foreignKeyName: "carts_converted_order_fk"
            columns: ["converted_order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "carts_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
        ]
      }
      categories: {
        Row: {
          created_at: string
          description: string | null
          id: string
          image_url: string | null
          name: string
          parent_id: string | null
          slug: string
          sort_order: number
          status: Database["public"]["Enums"]["city_status"]
          type: Database["public"]["Enums"]["category_type"]
          updated_at: string
        }
        Insert: {
          created_at?: string
          description?: string | null
          id?: string
          image_url?: string | null
          name: string
          parent_id?: string | null
          slug: string
          sort_order?: number
          status?: Database["public"]["Enums"]["city_status"]
          type: Database["public"]["Enums"]["category_type"]
          updated_at?: string
        }
        Update: {
          created_at?: string
          description?: string | null
          id?: string
          image_url?: string | null
          name?: string
          parent_id?: string | null
          slug?: string
          sort_order?: number
          status?: Database["public"]["Enums"]["city_status"]
          type?: Database["public"]["Enums"]["category_type"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "categories_parent_id_fkey"
            columns: ["parent_id"]
            isOneToOne: false
            referencedRelation: "categories"
            referencedColumns: ["id"]
          },
        ]
      }
      cities: {
        Row: {
          country_code: string
          created_at: string
          currency: string
          id: string
          name: string
          state: string
          status: Database["public"]["Enums"]["city_status"]
          timezone: string
          updated_at: string
        }
        Insert: {
          country_code?: string
          created_at?: string
          currency?: string
          id?: string
          name: string
          state: string
          status?: Database["public"]["Enums"]["city_status"]
          timezone?: string
          updated_at?: string
        }
        Update: {
          country_code?: string
          created_at?: string
          currency?: string
          id?: string
          name?: string
          state?: string
          status?: Database["public"]["Enums"]["city_status"]
          timezone?: string
          updated_at?: string
        }
        Relationships: []
      }
      customers: {
        Row: {
          created_at: string
          id: string
          marketing_consent: boolean
          preferred_currency: string
          profile_id: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          marketing_consent?: boolean
          preferred_currency?: string
          profile_id: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          marketing_consent?: boolean
          preferred_currency?: string
          profile_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "customers_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      listing_options: {
        Row: {
          capability_required: string | null
          configuration: Json
          currency: string
          id: string
          is_required: boolean
          label: string
          listing_id: string
          option_type: string
          preparation_minutes_delta: number
          price_adjustment_amount_minor: number
          status: Database["public"]["Enums"]["city_status"]
        }
        Insert: {
          capability_required?: string | null
          configuration?: Json
          currency?: string
          id?: string
          is_required?: boolean
          label: string
          listing_id: string
          option_type: string
          preparation_minutes_delta?: number
          price_adjustment_amount_minor?: number
          status?: Database["public"]["Enums"]["city_status"]
        }
        Update: {
          capability_required?: string | null
          configuration?: Json
          currency?: string
          id?: string
          is_required?: boolean
          label?: string
          listing_id?: string
          option_type?: string
          preparation_minutes_delta?: number
          price_adjustment_amount_minor?: number
          status?: Database["public"]["Enums"]["city_status"]
        }
        Relationships: [
          {
            foreignKeyName: "listing_options_listing_id_fkey"
            columns: ["listing_id"]
            isOneToOne: false
            referencedRelation: "listings"
            referencedColumns: ["id"]
          },
        ]
      }
      listing_variants: {
        Row: {
          attributes: Json | null
          created_at: string
          currency: string
          id: string
          listing_id: string
          name: string
          price_adjustment_amount_minor: number
          sku: string | null
          status: Database["public"]["Enums"]["city_status"]
          updated_at: string
        }
        Insert: {
          attributes?: Json | null
          created_at?: string
          currency?: string
          id?: string
          listing_id: string
          name: string
          price_adjustment_amount_minor?: number
          sku?: string | null
          status?: Database["public"]["Enums"]["city_status"]
          updated_at?: string
        }
        Update: {
          attributes?: Json | null
          created_at?: string
          currency?: string
          id?: string
          listing_id?: string
          name?: string
          price_adjustment_amount_minor?: number
          sku?: string | null
          status?: Database["public"]["Enums"]["city_status"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "listing_variants_listing_id_fkey"
            columns: ["listing_id"]
            isOneToOne: false
            referencedRelation: "listings"
            referencedColumns: ["id"]
          },
        ]
      }
      listing_zones: {
        Row: {
          listing_id: string
          status: Database["public"]["Enums"]["city_status"]
          zone_id: string
        }
        Insert: {
          listing_id: string
          status?: Database["public"]["Enums"]["city_status"]
          zone_id: string
        }
        Update: {
          listing_id?: string
          status?: Database["public"]["Enums"]["city_status"]
          zone_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "listing_zones_listing_id_fkey"
            columns: ["listing_id"]
            isOneToOne: false
            referencedRelation: "listings"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "listing_zones_zone_id_fkey"
            columns: ["zone_id"]
            isOneToOne: false
            referencedRelation: "zones"
            referencedColumns: ["id"]
          },
        ]
      }
      listings: {
        Row: {
          archived_at: string | null
          availability_mode: Database["public"]["Enums"]["availability_mode"]
          base_price_amount_minor: number | null
          cancellation_note: string | null
          created_at: string
          currency: string
          customer_description: string | null
          customer_title: string
          external_source_id: string | null
          id: string
          last_verified_at: string | null
          partner_id: string | null
          paused_at: string | null
          preparation_minutes: number | null
          product_id: string
          published_at: string | null
          source_type: Database["public"]["Enums"]["listing_source_type"]
          status: Database["public"]["Enums"]["listing_status"]
          substitution_policy: string | null
          updated_at: string
          verification_expires_at: string | null
        }
        Insert: {
          archived_at?: string | null
          availability_mode?: Database["public"]["Enums"]["availability_mode"]
          base_price_amount_minor?: number | null
          cancellation_note?: string | null
          created_at?: string
          currency?: string
          customer_description?: string | null
          customer_title: string
          external_source_id?: string | null
          id?: string
          last_verified_at?: string | null
          partner_id?: string | null
          paused_at?: string | null
          preparation_minutes?: number | null
          product_id: string
          published_at?: string | null
          source_type: Database["public"]["Enums"]["listing_source_type"]
          status?: Database["public"]["Enums"]["listing_status"]
          substitution_policy?: string | null
          updated_at?: string
          verification_expires_at?: string | null
        }
        Update: {
          archived_at?: string | null
          availability_mode?: Database["public"]["Enums"]["availability_mode"]
          base_price_amount_minor?: number | null
          cancellation_note?: string | null
          created_at?: string
          currency?: string
          customer_description?: string | null
          customer_title?: string
          external_source_id?: string | null
          id?: string
          last_verified_at?: string | null
          partner_id?: string | null
          paused_at?: string | null
          preparation_minutes?: number | null
          product_id?: string
          published_at?: string | null
          source_type?: Database["public"]["Enums"]["listing_source_type"]
          status?: Database["public"]["Enums"]["listing_status"]
          substitution_policy?: string | null
          updated_at?: string
          verification_expires_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "listings_partner_id_fkey"
            columns: ["partner_id"]
            isOneToOne: false
            referencedRelation: "partners"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "listings_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
        ]
      }
      media_assets: {
        Row: {
          alt_text: string | null
          created_at: string
          created_by: string | null
          height: number | null
          id: string
          mime_type: string | null
          owner_id: string
          owner_type: string
          size_bytes: number | null
          sort_order: number
          status: Database["public"]["Enums"]["city_status"]
          storage_bucket: string
          storage_path: string
          visibility: Database["public"]["Enums"]["media_visibility"]
          width: number | null
        }
        Insert: {
          alt_text?: string | null
          created_at?: string
          created_by?: string | null
          height?: number | null
          id?: string
          mime_type?: string | null
          owner_id: string
          owner_type: string
          size_bytes?: number | null
          sort_order?: number
          status?: Database["public"]["Enums"]["city_status"]
          storage_bucket?: string
          storage_path: string
          visibility?: Database["public"]["Enums"]["media_visibility"]
          width?: number | null
        }
        Update: {
          alt_text?: string | null
          created_at?: string
          created_by?: string | null
          height?: number | null
          id?: string
          mime_type?: string | null
          owner_id?: string
          owner_type?: string
          size_bytes?: number | null
          sort_order?: number
          status?: Database["public"]["Enums"]["city_status"]
          storage_bucket?: string
          storage_path?: string
          visibility?: Database["public"]["Enums"]["media_visibility"]
          width?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "media_assets_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      order_items: {
        Row: {
          created_at: string
          currency: string
          id: string
          listing_id: string
          options_snapshot: Json
          order_id: string
          personalization_snapshot: Json | null
          product_id: string
          product_snapshot: Json
          quantity: number
          total_price_amount_minor: number
          unit_price_amount_minor: number
          variant_id: string | null
          variant_snapshot: Json | null
        }
        Insert: {
          created_at?: string
          currency: string
          id?: string
          listing_id: string
          options_snapshot: Json
          order_id: string
          personalization_snapshot?: Json | null
          product_id: string
          product_snapshot: Json
          quantity: number
          total_price_amount_minor: number
          unit_price_amount_minor: number
          variant_id?: string | null
          variant_snapshot?: Json | null
        }
        Update: {
          created_at?: string
          currency?: string
          id?: string
          listing_id?: string
          options_snapshot?: Json
          order_id?: string
          personalization_snapshot?: Json | null
          product_id?: string
          product_snapshot?: Json
          quantity?: number
          total_price_amount_minor?: number
          unit_price_amount_minor?: number
          variant_id?: string | null
          variant_snapshot?: Json | null
        }
        Relationships: [
          {
            foreignKeyName: "order_items_listing_id_fkey"
            columns: ["listing_id"]
            isOneToOne: false
            referencedRelation: "listings"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "order_items_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "order_items_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "order_items_variant_id_fkey"
            columns: ["variant_id"]
            isOneToOne: false
            referencedRelation: "listing_variants"
            referencedColumns: ["id"]
          },
        ]
      }
      order_state_history: {
        Row: {
          actor_id: string
          actor_type: string
          created_at: string
          from_state: Database["public"]["Enums"]["order_state"] | null
          id: string
          idempotency_key: string
          order_id: string
          reason_code: string
          request_id: string
          to_state: Database["public"]["Enums"]["order_state"]
        }
        Insert: {
          actor_id: string
          actor_type: string
          created_at?: string
          from_state?: Database["public"]["Enums"]["order_state"] | null
          id?: string
          idempotency_key: string
          order_id: string
          reason_code: string
          request_id: string
          to_state: Database["public"]["Enums"]["order_state"]
        }
        Update: {
          actor_id?: string
          actor_type?: string
          created_at?: string
          from_state?: Database["public"]["Enums"]["order_state"] | null
          id?: string
          idempotency_key?: string
          order_id?: string
          reason_code?: string
          request_id?: string
          to_state?: Database["public"]["Enums"]["order_state"]
        }
        Relationships: [
          {
            foreignKeyName: "order_state_history_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "order_state_history_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
        ]
      }
      orders: {
        Row: {
          availability_status: Database["public"]["Enums"]["quote_availability_status"]
          created_at: string
          currency: string
          current_state: Database["public"]["Enums"]["order_state"]
          customer_id: string
          delivery_address_snapshot: Json
          delivery_amount_minor: number | null
          discount_amount_minor: number
          id: string
          idempotency_key: string
          pending_components: Json
          public_reference: string
          quote_id: string
          recipient_snapshot: Json
          request_hash: string
          requested_delivery_at: string
          service_amount_minor: number | null
          source_cart_id: string
          source_cart_version: number
          subtotal_amount_minor: number
          total_is_final: boolean
          total_known_amount_minor: number
          updated_at: string
          version: number
        }
        Insert: {
          availability_status: Database["public"]["Enums"]["quote_availability_status"]
          created_at?: string
          currency: string
          current_state?: Database["public"]["Enums"]["order_state"]
          customer_id: string
          delivery_address_snapshot: Json
          delivery_amount_minor?: number | null
          discount_amount_minor?: number
          id?: string
          idempotency_key: string
          pending_components: Json
          public_reference?: string
          quote_id: string
          recipient_snapshot: Json
          request_hash: string
          requested_delivery_at: string
          service_amount_minor?: number | null
          source_cart_id: string
          source_cart_version: number
          subtotal_amount_minor: number
          total_is_final?: boolean
          total_known_amount_minor: number
          updated_at?: string
          version?: number
        }
        Update: {
          availability_status?: Database["public"]["Enums"]["quote_availability_status"]
          created_at?: string
          currency?: string
          current_state?: Database["public"]["Enums"]["order_state"]
          customer_id?: string
          delivery_address_snapshot?: Json
          delivery_amount_minor?: number | null
          discount_amount_minor?: number
          id?: string
          idempotency_key?: string
          pending_components?: Json
          public_reference?: string
          quote_id?: string
          recipient_snapshot?: Json
          request_hash?: string
          requested_delivery_at?: string
          service_amount_minor?: number | null
          source_cart_id?: string
          source_cart_version?: number
          subtotal_amount_minor?: number
          total_is_final?: boolean
          total_known_amount_minor?: number
          updated_at?: string
          version?: number
        }
        Relationships: [
          {
            foreignKeyName: "orders_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_quote_id_fkey"
            columns: ["quote_id"]
            isOneToOne: true
            referencedRelation: "quotes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_source_cart_id_fkey"
            columns: ["source_cart_id"]
            isOneToOne: true
            referencedRelation: "carts"
            referencedColumns: ["id"]
          },
        ]
      }
      partner_capabilities: {
        Row: {
          approved_at: string | null
          approved_by: string | null
          capability_code: string
          created_at: string
          id: string
          partner_id: string
          restrictions: Json | null
          status: Database["public"]["Enums"]["partner_capability_status"]
          updated_at: string
        }
        Insert: {
          approved_at?: string | null
          approved_by?: string | null
          capability_code: string
          created_at?: string
          id?: string
          partner_id: string
          restrictions?: Json | null
          status?: Database["public"]["Enums"]["partner_capability_status"]
          updated_at?: string
        }
        Update: {
          approved_at?: string | null
          approved_by?: string | null
          capability_code?: string
          created_at?: string
          id?: string
          partner_id?: string
          restrictions?: Json | null
          status?: Database["public"]["Enums"]["partner_capability_status"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "partner_capabilities_approved_by_fkey"
            columns: ["approved_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "partner_capabilities_partner_id_fkey"
            columns: ["partner_id"]
            isOneToOne: false
            referencedRelation: "partners"
            referencedColumns: ["id"]
          },
        ]
      }
      partner_capacity: {
        Row: {
          active_count: number
          capacity_type: string
          capacity_value: number
          id: string
          partner_id: string
          updated_at: string
          updated_by: string | null
          valid_from: string | null
          valid_until: string | null
        }
        Insert: {
          active_count?: number
          capacity_type: string
          capacity_value: number
          id?: string
          partner_id: string
          updated_at?: string
          updated_by?: string | null
          valid_from?: string | null
          valid_until?: string | null
        }
        Update: {
          active_count?: number
          capacity_type?: string
          capacity_value?: number
          id?: string
          partner_id?: string
          updated_at?: string
          updated_by?: string | null
          valid_from?: string | null
          valid_until?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "partner_capacity_partner_id_fkey"
            columns: ["partner_id"]
            isOneToOne: false
            referencedRelation: "partners"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "partner_capacity_updated_by_fkey"
            columns: ["updated_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      partner_schedule_exceptions: {
        Row: {
          closes_at: string | null
          created_at: string
          exception_date: string
          id: string
          is_closed: boolean
          opens_at: string | null
          partner_id: string
          reason: string | null
          updated_at: string
        }
        Insert: {
          closes_at?: string | null
          created_at?: string
          exception_date: string
          id?: string
          is_closed?: boolean
          opens_at?: string | null
          partner_id: string
          reason?: string | null
          updated_at?: string
        }
        Update: {
          closes_at?: string | null
          created_at?: string
          exception_date?: string
          id?: string
          is_closed?: boolean
          opens_at?: string | null
          partner_id?: string
          reason?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "partner_schedule_exceptions_partner_id_fkey"
            columns: ["partner_id"]
            isOneToOne: false
            referencedRelation: "partners"
            referencedColumns: ["id"]
          },
        ]
      }
      partner_schedules: {
        Row: {
          closes_at: string | null
          created_at: string
          day_of_week: number
          effective_from: string | null
          effective_to: string | null
          id: string
          is_closed: boolean
          opens_at: string | null
          partner_id: string
          updated_at: string
        }
        Insert: {
          closes_at?: string | null
          created_at?: string
          day_of_week: number
          effective_from?: string | null
          effective_to?: string | null
          id?: string
          is_closed?: boolean
          opens_at?: string | null
          partner_id: string
          updated_at?: string
        }
        Update: {
          closes_at?: string | null
          created_at?: string
          day_of_week?: number
          effective_from?: string | null
          effective_to?: string | null
          id?: string
          is_closed?: boolean
          opens_at?: string | null
          partner_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "partner_schedules_partner_id_fkey"
            columns: ["partner_id"]
            isOneToOne: false
            referencedRelation: "partners"
            referencedColumns: ["id"]
          },
        ]
      }
      partners: {
        Row: {
          address_id: string | null
          agreement_accepted_at: string | null
          agreement_version: string | null
          city_id: string
          closed_at: string | null
          created_at: string
          email: string | null
          id: string
          legal_name: string | null
          paused_at: string | null
          payout_currency: string
          phone: string | null
          primary_zone_id: string | null
          public_name: string
          slug: string
          status: Database["public"]["Enums"]["partner_status"]
          suspended_at: string | null
          timezone: string | null
          updated_at: string
        }
        Insert: {
          address_id?: string | null
          agreement_accepted_at?: string | null
          agreement_version?: string | null
          city_id: string
          closed_at?: string | null
          created_at?: string
          email?: string | null
          id?: string
          legal_name?: string | null
          paused_at?: string | null
          payout_currency?: string
          phone?: string | null
          primary_zone_id?: string | null
          public_name: string
          slug: string
          status?: Database["public"]["Enums"]["partner_status"]
          suspended_at?: string | null
          timezone?: string | null
          updated_at?: string
        }
        Update: {
          address_id?: string | null
          agreement_accepted_at?: string | null
          agreement_version?: string | null
          city_id?: string
          closed_at?: string | null
          created_at?: string
          email?: string | null
          id?: string
          legal_name?: string | null
          paused_at?: string | null
          payout_currency?: string
          phone?: string | null
          primary_zone_id?: string | null
          public_name?: string
          slug?: string
          status?: Database["public"]["Enums"]["partner_status"]
          suspended_at?: string | null
          timezone?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "partners_address_id_fkey"
            columns: ["address_id"]
            isOneToOne: false
            referencedRelation: "addresses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "partners_city_id_fkey"
            columns: ["city_id"]
            isOneToOne: false
            referencedRelation: "cities"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "partners_primary_zone_id_fkey"
            columns: ["primary_zone_id"]
            isOneToOne: false
            referencedRelation: "zones"
            referencedColumns: ["id"]
          },
        ]
      }
      product_tags: {
        Row: {
          product_id: string
          tag_id: string
        }
        Insert: {
          product_id: string
          tag_id: string
        }
        Update: {
          product_id?: string
          tag_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "product_tags_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "product_tags_tag_id_fkey"
            columns: ["tag_id"]
            isOneToOne: false
            referencedRelation: "tags"
            referencedColumns: ["id"]
          },
        ]
      }
      products: {
        Row: {
          archived_at: string | null
          attributes: Json | null
          brand: string | null
          category_id: string | null
          created_at: string
          description: string | null
          dimensions: Json | null
          id: string
          is_fragile: boolean
          is_perishable: boolean
          is_restricted: boolean
          name: string
          product_type: Database["public"]["Enums"]["product_type"]
          slug: string
          status: Database["public"]["Enums"]["product_status"]
          updated_at: string
          weight_grams: number | null
        }
        Insert: {
          archived_at?: string | null
          attributes?: Json | null
          brand?: string | null
          category_id?: string | null
          created_at?: string
          description?: string | null
          dimensions?: Json | null
          id?: string
          is_fragile?: boolean
          is_perishable?: boolean
          is_restricted?: boolean
          name: string
          product_type: Database["public"]["Enums"]["product_type"]
          slug: string
          status?: Database["public"]["Enums"]["product_status"]
          updated_at?: string
          weight_grams?: number | null
        }
        Update: {
          archived_at?: string | null
          attributes?: Json | null
          brand?: string | null
          category_id?: string | null
          created_at?: string
          description?: string | null
          dimensions?: Json | null
          id?: string
          is_fragile?: boolean
          is_perishable?: boolean
          is_restricted?: boolean
          name?: string
          product_type?: Database["public"]["Enums"]["product_type"]
          slug?: string
          status?: Database["public"]["Enums"]["product_status"]
          updated_at?: string
          weight_grams?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "products_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "categories"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          auth_user_id: string
          created_at: string
          default_role: Database["public"]["Enums"]["user_role"]
          display_name: string | null
          email: string | null
          id: string
          last_login_at: string | null
          phone: string | null
          status: Database["public"]["Enums"]["profile_status"]
          updated_at: string
        }
        Insert: {
          auth_user_id: string
          created_at?: string
          default_role?: Database["public"]["Enums"]["user_role"]
          display_name?: string | null
          email?: string | null
          id?: string
          last_login_at?: string | null
          phone?: string | null
          status?: Database["public"]["Enums"]["profile_status"]
          updated_at?: string
        }
        Update: {
          auth_user_id?: string
          created_at?: string
          default_role?: Database["public"]["Enums"]["user_role"]
          display_name?: string | null
          email?: string | null
          id?: string
          last_login_at?: string | null
          phone?: string | null
          status?: Database["public"]["Enums"]["profile_status"]
          updated_at?: string
        }
        Relationships: []
      }
      quote_items: {
        Row: {
          availability_status: Database["public"]["Enums"]["quote_availability_status"]
          created_at: string
          currency: string
          id: string
          line_total_amount_minor: number
          listing_id: string
          options_snapshot: Json
          product_id: string
          product_snapshot: Json
          quantity: number
          quote_id: string
          unit_adjustments_amount_minor: number
          unit_base_amount_minor: number
          unit_final_amount_minor: number
          variant_id: string | null
          variant_snapshot: Json | null
        }
        Insert: {
          availability_status: Database["public"]["Enums"]["quote_availability_status"]
          created_at?: string
          currency: string
          id?: string
          line_total_amount_minor: number
          listing_id: string
          options_snapshot?: Json
          product_id: string
          product_snapshot: Json
          quantity: number
          quote_id: string
          unit_adjustments_amount_minor: number
          unit_base_amount_minor: number
          unit_final_amount_minor: number
          variant_id?: string | null
          variant_snapshot?: Json | null
        }
        Update: {
          availability_status?: Database["public"]["Enums"]["quote_availability_status"]
          created_at?: string
          currency?: string
          id?: string
          line_total_amount_minor?: number
          listing_id?: string
          options_snapshot?: Json
          product_id?: string
          product_snapshot?: Json
          quantity?: number
          quote_id?: string
          unit_adjustments_amount_minor?: number
          unit_base_amount_minor?: number
          unit_final_amount_minor?: number
          variant_id?: string | null
          variant_snapshot?: Json | null
        }
        Relationships: [
          {
            foreignKeyName: "quote_items_listing_id_fkey"
            columns: ["listing_id"]
            isOneToOne: false
            referencedRelation: "listings"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quote_items_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quote_items_quote_id_fkey"
            columns: ["quote_id"]
            isOneToOne: false
            referencedRelation: "quotes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quote_items_variant_id_fkey"
            columns: ["variant_id"]
            isOneToOne: false
            referencedRelation: "listing_variants"
            referencedColumns: ["id"]
          },
        ]
      }
      quotes: {
        Row: {
          availability_status: Database["public"]["Enums"]["quote_availability_status"]
          created_at: string
          currency: string
          customer_id: string
          delivery_amount_minor: number | null
          discount_amount_minor: number
          expires_at: string | null
          id: string
          idempotency_key: string
          invalidated_at: string | null
          invalidation_reason: string | null
          pending_components: Json
          pricing_version: string
          public_reference: string
          requested_delivery_at: string | null
          service_amount_minor: number | null
          status: Database["public"]["Enums"]["quote_status"]
          subtotal_amount_minor: number
          total_is_final: boolean
          total_known_amount_minor: number
          updated_at: string
          zone_id: string | null
        }
        Insert: {
          availability_status: Database["public"]["Enums"]["quote_availability_status"]
          created_at?: string
          currency: string
          customer_id: string
          delivery_amount_minor?: number | null
          discount_amount_minor?: number
          expires_at?: string | null
          id?: string
          idempotency_key: string
          invalidated_at?: string | null
          invalidation_reason?: string | null
          pending_components?: Json
          pricing_version: string
          public_reference?: string
          requested_delivery_at?: string | null
          service_amount_minor?: number | null
          status: Database["public"]["Enums"]["quote_status"]
          subtotal_amount_minor: number
          total_is_final?: boolean
          total_known_amount_minor: number
          updated_at?: string
          zone_id?: string | null
        }
        Update: {
          availability_status?: Database["public"]["Enums"]["quote_availability_status"]
          created_at?: string
          currency?: string
          customer_id?: string
          delivery_amount_minor?: number | null
          discount_amount_minor?: number
          expires_at?: string | null
          id?: string
          idempotency_key?: string
          invalidated_at?: string | null
          invalidation_reason?: string | null
          pending_components?: Json
          pricing_version?: string
          public_reference?: string
          requested_delivery_at?: string | null
          service_amount_minor?: number | null
          status?: Database["public"]["Enums"]["quote_status"]
          subtotal_amount_minor?: number
          total_is_final?: boolean
          total_known_amount_minor?: number
          updated_at?: string
          zone_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "quotes_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quotes_zone_id_fkey"
            columns: ["zone_id"]
            isOneToOne: false
            referencedRelation: "zones"
            referencedColumns: ["id"]
          },
        ]
      }
      recipients: {
        Row: {
          archived_at: string | null
          consent_basis: string | null
          created_at: string
          customer_id: string
          id: string
          name: string
          notes: string | null
          phone: string | null
          relationship: string | null
          surprise_mode: Database["public"]["Enums"]["recipient_surprise_mode"]
          updated_at: string
        }
        Insert: {
          archived_at?: string | null
          consent_basis?: string | null
          created_at?: string
          customer_id: string
          id?: string
          name: string
          notes?: string | null
          phone?: string | null
          relationship?: string | null
          surprise_mode?: Database["public"]["Enums"]["recipient_surprise_mode"]
          updated_at?: string
        }
        Update: {
          archived_at?: string | null
          consent_basis?: string | null
          created_at?: string
          customer_id?: string
          id?: string
          name?: string
          notes?: string | null
          phone?: string | null
          relationship?: string | null
          surprise_mode?: Database["public"]["Enums"]["recipient_surprise_mode"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "recipients_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
        ]
      }
      tags: {
        Row: {
          created_at: string
          id: string
          name: string
          slug: string
          status: Database["public"]["Enums"]["city_status"]
          type: Database["public"]["Enums"]["tag_type"]
        }
        Insert: {
          created_at?: string
          id?: string
          name: string
          slug: string
          status?: Database["public"]["Enums"]["city_status"]
          type: Database["public"]["Enums"]["tag_type"]
        }
        Update: {
          created_at?: string
          id?: string
          name?: string
          slug?: string
          status?: Database["public"]["Enums"]["city_status"]
          type?: Database["public"]["Enums"]["tag_type"]
        }
        Relationships: []
      }
      user_roles: {
        Row: {
          created_at: string
          created_by: string | null
          id: string
          partner_id: string | null
          profile_id: string
          revoked_at: string | null
          role: Database["public"]["Enums"]["user_role"]
          status: Database["public"]["Enums"]["user_role_assignment_status"]
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          id?: string
          partner_id?: string | null
          profile_id: string
          revoked_at?: string | null
          role: Database["public"]["Enums"]["user_role"]
          status?: Database["public"]["Enums"]["user_role_assignment_status"]
        }
        Update: {
          created_at?: string
          created_by?: string | null
          id?: string
          partner_id?: string | null
          profile_id?: string
          revoked_at?: string | null
          role?: Database["public"]["Enums"]["user_role"]
          status?: Database["public"]["Enums"]["user_role_assignment_status"]
        }
        Relationships: [
          {
            foreignKeyName: "user_roles_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_roles_partner_id_fkey"
            columns: ["partner_id"]
            isOneToOne: false
            referencedRelation: "partners"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_roles_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      zones: {
        Row: {
          boundary_geojson: Json | null
          city_id: string
          created_at: string
          id: string
          mphora_enabled: boolean
          name: string
          operating_hours: Json | null
          postal_codes: string[] | null
          slug: string
          status: Database["public"]["Enums"]["zone_status"]
          updated_at: string
        }
        Insert: {
          boundary_geojson?: Json | null
          city_id: string
          created_at?: string
          id?: string
          mphora_enabled?: boolean
          name: string
          operating_hours?: Json | null
          postal_codes?: string[] | null
          slug: string
          status?: Database["public"]["Enums"]["zone_status"]
          updated_at?: string
        }
        Update: {
          boundary_geojson?: Json | null
          city_id?: string
          created_at?: string
          id?: string
          mphora_enabled?: boolean
          name?: string
          operating_hours?: Json | null
          postal_codes?: string[] | null
          slug?: string
          status?: Database["public"]["Enums"]["zone_status"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "zones_city_id_fkey"
            columns: ["city_id"]
            isOneToOne: false
            referencedRelation: "cities"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      auth_profile_id: { Args: never; Returns: string }
      auth_roles: {
        Args: never
        Returns: Database["public"]["Enums"]["user_role"][]
      }
      auth_uid: { Args: never; Returns: string }
      calculate_public_quote: { Args: { p_request: Json }; Returns: Json }
      create_customer_draft_order: {
        Args: {
          p_cart_id: string
          p_expected_version: number
          p_idempotency_key: string
          p_request_id: string
        }
        Returns: Json
      }
      create_customer_quote: {
        Args: { p_idempotency_key: string; p_request: Json }
        Returns: Json
      }
      get_customer_cart: { Args: never; Returns: Json }
      get_customer_order: { Args: { p_order_id: string }; Returns: Json }
      get_customer_quote: { Args: { p_quote_id: string }; Returns: Json }
      get_public_catalog: {
        Args: {
          p_category_slug?: string
          p_listing_slug?: string
          p_result_limit?: number
          p_result_offset?: number
        }
        Returns: {
          category_id: string
          category_name: string
          category_slug: string
          currency: string
          featured: boolean
          full_description: string
          image_alt: string
          image_url: string
          listing_id: string
          mphora_candidate: boolean
          name: string
          personalization_available: boolean
          price_amount_minor: number
          product_id: string
          scheduled_delivery_available: boolean
          short_description: string
          slug: string
        }[]
      }
      get_public_catalog_categories: {
        Args: never
        Returns: {
          description: string
          id: string
          image_url: string
          listing_count: number
          name: string
          slug: string
        }[]
      }
      get_public_quote_configuration: {
        Args: { p_listing_id: string }
        Returns: Json
      }
      has_role: {
        Args: { check_role: Database["public"]["Enums"]["user_role"] }
        Returns: boolean
      }
      is_mpho_staff: { Args: never; Returns: boolean }
      mutate_customer_cart: {
        Args: {
          p_expected_version: number
          p_operation: string
          p_payload: Json
        }
        Returns: Json
      }
      phase6_cart_json: { Args: { p_cart_id: string }; Returns: Json }
      phase6_customer_id: { Args: never; Returns: string }
      phase6_order_json: { Args: { p_order_id: string }; Returns: Json }
      phase6_profile_id: { Args: never; Returns: string }
    }
    Enums: {
      address_owner_type:
        | "customer"
        | "recipient"
        | "partner"
        | "order_snapshot"
      availability_mode:
        | "tracked_stock"
        | "partner_confirmation"
        | "scheduled_capacity"
        | "external_by_order"
        | "unavailable"
      cart_status: "active" | "converted" | "abandoned"
      category_type: "product" | "occasion" | "recipient" | "style"
      city_status: "active" | "planned" | "suspended"
      customer_status: "active" | "suspended" | "deleted"
      listing_source_type:
        | "partner_local"
        | "external_curated"
        | "mpho_owned_future"
      listing_status:
        | "draft"
        | "submitted"
        | "under_review"
        | "changes_requested"
        | "approved"
        | "published"
        | "paused"
        | "rejected"
        | "archived"
      media_visibility: "public" | "partner_only" | "internal"
      order_state: "draft"
      partner_capability_status: "active" | "suspended" | "revoked"
      partner_status:
        | "pending_onboarding"
        | "active"
        | "paused"
        | "suspended"
        | "closed"
      product_status: "draft" | "active" | "archived"
      product_type: "product" | "service" | "bundle" | "add_on"
      profile_status: "active" | "suspended" | "deleted"
      quote_availability_status: "eligible" | "requires_review" | "unavailable"
      quote_status: "valid" | "requires_review" | "expired" | "invalidated"
      recipient_surprise_mode: "none" | "full_surprise" | "partial_surprise"
      tag_type: "style" | "delivery" | "feature" | "seasonal"
      user_role:
        | "customer"
        | "partner_operator"
        | "partner_admin"
        | "courier"
        | "mpho_operator"
        | "mpho_admin"
        | "service_account"
      user_role_assignment_status: "active" | "revoked"
      zone_status: "active" | "planned" | "suspended"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      address_owner_type: [
        "customer",
        "recipient",
        "partner",
        "order_snapshot",
      ],
      availability_mode: [
        "tracked_stock",
        "partner_confirmation",
        "scheduled_capacity",
        "external_by_order",
        "unavailable",
      ],
      cart_status: ["active", "converted", "abandoned"],
      category_type: ["product", "occasion", "recipient", "style"],
      city_status: ["active", "planned", "suspended"],
      customer_status: ["active", "suspended", "deleted"],
      listing_source_type: [
        "partner_local",
        "external_curated",
        "mpho_owned_future",
      ],
      listing_status: [
        "draft",
        "submitted",
        "under_review",
        "changes_requested",
        "approved",
        "published",
        "paused",
        "rejected",
        "archived",
      ],
      media_visibility: ["public", "partner_only", "internal"],
      order_state: ["draft"],
      partner_capability_status: ["active", "suspended", "revoked"],
      partner_status: [
        "pending_onboarding",
        "active",
        "paused",
        "suspended",
        "closed",
      ],
      product_status: ["draft", "active", "archived"],
      product_type: ["product", "service", "bundle", "add_on"],
      profile_status: ["active", "suspended", "deleted"],
      quote_availability_status: ["eligible", "requires_review", "unavailable"],
      quote_status: ["valid", "requires_review", "expired", "invalidated"],
      recipient_surprise_mode: ["none", "full_surprise", "partial_surprise"],
      tag_type: ["style", "delivery", "feature", "seasonal"],
      user_role: [
        "customer",
        "partner_operator",
        "partner_admin",
        "courier",
        "mpho_operator",
        "mpho_admin",
        "service_account",
      ],
      user_role_assignment_status: ["active", "revoked"],
      zone_status: ["active", "planned", "suspended"],
    },
  },
} as const

