#!/bin/sh
set -eu

expected="packages/database/types.generated.ts"
temporary="$(mktemp)"
trap 'rm -f "$temporary"' EXIT

{
  printf '%s\n' '// AUTO-GENERATED by `pnpm db:types`. Do not edit manually.'
  supabase gen types typescript --local --schema public
} > "$temporary"

diff -u "$expected" "$temporary"
