#!/bin/sh
set -eu

output="packages/database/types.generated.ts"
temporary="$(mktemp)"
trap 'rm -f "$temporary"' EXIT

supabase gen types typescript --local --schema public > "$temporary"
{
  printf '%s\n' '// AUTO-GENERATED by `pnpm db:types`. Do not edit manually.'
  cat "$temporary"
} > "$output"
